version: '3.8'

services:
      
  # The MySQL service
  mysql:
    image: mysql:5.7 
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d 
    environment:
      MYSQL_ROOT_PASSWORD: Pirate65 
      MYSQL_DATABASE: enter_data_db
    ports:
      - "3306:3306" 

  # The Enter Data Web App service
  enter_data_webapp:
    build: ./EnterDataWebApp 
    ports:
      - "3000:3000" 
    depends_on:
      - mysql 
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Pirate65
      DB_NAME: enter_data_db
    command: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60s", "node", "app.js"]

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pirate65
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  analytics_service:
    build: ./AnalyticsService
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - mongodb


  show_results_webapp:
    build: ./ShowResultsWebApp
    ports:
      - "3002:3002"
    depends_on:
      - mongodb


volumes:
  mongodb_data:
  mysql_data: 
